[[assets]]
name = "font_7px"
path = "assets/font_7px_rgba.tga"
type = "sprite_font"

[[assets]]
name = "player"
path = "assets/ss_player.toml"
type = "sprite_sheet"

[[assets]]
name = "skelly"
path = "assets/ss_skelly.toml"
type = "sprite_sheet"

[[assets]]
name = "bullet"
path = "assets/bullet_rgba.tga"
type = "sprite"

[[assets]]
name = "tiled_wall_16x16"
path = "assets/tiled_wall_16x16.tga"
type = "sprite"

[[assets]]
name = "snd_primary_fire"
path = "assets/primary_fire.wav"
type = "audio_clip"

[[assets]]
name = "theme_music"
path = "assets/theme.ogg"
type = "audio_clip"
