[[assets]]
name = "font_7px"
path = "assets/font_7px_rgba.tga"
type = "sprite_font"

[[assets]]
name = "player"
path = "assets/ss_player.toml"
type = "sprite_sheet"

[[assets]]
name = "skelly"
path = "assets/ss_skelly.toml"
type = "sprite_sheet"

[[assets]]
name = "bullet"
path = "assets/bullet_rgba.tga"
type = "sprite"

[[assets]]
name = "tiled_wall_64x64"
path = "assets/tiled_wall_64x64.tga"
type = "sprite"

[[assets]]
name = "machines_floor_64x64"
path = "assets/machines_floor_64x64.tga"
type = "sprite"

[[assets]]
name = "shadowy_wall_16x16"
path = "assets/shadowy_wall_16x16.tga"
type = "sprite"

[[assets]]
name = "grass_dirt_block"
path = "assets/grass_dirt_block.tga"
type = "sprite"

[[assets]]
name = "snd_primary_fire"
path = "assets/primary_fire.wav"
type = "sfx"

[[assets]]
name = "theme_music"
path = "assets/theme.ogg"
type = "music"
