[[assets]]
name = "pos_uv_vs"
path = "assets/shader/solid.vs.hlsl"
kind = "shader"
vertex_type = "posuv"
[[assets]]
name = "pos_uv_ps"
path = "assets/shader/solid.ps.hlsl"
kind = "shader"
[[assets]]
name = "pos_color_ps"
path = "assets/shader/pos_color.ps.hlsl"
kind = "shader"
[[assets]]
name = "pos_color_vs"
path = "assets/shader/pos_color.vs.hlsl"
kind = "shader"
vertex_type = "poscol"

[[assets]]
name = "font_7px"
path = "assets/image/font_7px_rgba.tga"
kind = "sprite_font"

[[assets]]
name = "player"
path = "assets/image/ss_player.toml"
kind = "sprite_sheet"

[[assets]]
name = "skelly"
path = "assets/image/ss_skelly.toml"
kind = "sprite_sheet"

[[assets]]
name = "roboid"
path = "assets/image/roboid.toml"
kind = "sprite_sheet"

[[assets]]
name = "bullet"
path = "assets/image/bullet_rgba.tga"
kind = "sprite"
scale = 2

[[assets]]
name = "tiled_wall_64x64"
path = "assets/image/tiled_wall_64x64.tga"
kind = "sprite"
scale = 1

[[assets]]
name = "machines_floor_64x64"
path = "assets/image/machines_floor_64x64.tga"
kind = "sprite"
scale = 1

[[assets]]
name = "shadowy_wall_16x16"
path = "assets/image/shadowy_wall_16x16.tga"
kind = "sprite"
scale = 1

[[assets]]
name = "grass_dirt_block"
path = "assets/image/grass_dirt_block.tga"
kind = "sprite"
scale = 1

[[assets]]
name = "snd_primary_fire"
path = "assets/sfx/primary_fire.wav"
kind = "sfx"

[[assets]]
name = "theme_music"
path = "assets/music/theme.ogg"
kind = "music"
