[[assets]]
name = "pos_uv_vs"
path = "assets/shader/solid.vs.hlsl"
kind = "shader"
vertex_type = "posuv"
[[assets]]
name = "pos_uv_ps"
path = "assets/shader/solid.ps.hlsl"
kind = "shader"
[[assets]]
name = "pos_color_ps"
path = "assets/shader/pos_color.ps.hlsl"
kind = "shader"
[[assets]]
name = "pos_color_vs"
path = "assets/shader/pos_color.vs.hlsl"
kind = "shader"
vertex_type = "poscol"
[[assets]]
name = "fullscreen_vs"
path = "assets/shader/fullscreen.vs.hlsl"
kind = "shader"
vertex_type = "posuv"

[[assets]]
name = "player"
path = "assets/image/ss_player.toml"
kind = "sprite_sheet"

[[assets]]
name = "font_7px"
path = "assets/image/font_7px_rgba.tga"
kind = "sprite_font"

[[assets]]
name = "metro"
path = "assets/image/metro_1080p.tga"
kind = "sprite"

[[assets]]
name = "rgba_test"
path = "assets/image/rgba.tga"
kind = "sprite"
