[[assets]]
name = "vs_pos_uv"
path = "assets/shader/solid.vs.hlsl"
kind = "shader"
vertex_type = "posuv"
[[assets]]
name = "ps_pos_uv"
path = "assets/shader/solid.ps.hlsl"
kind = "shader"
[[assets]]
name = "vs_pos_color"
path = "assets/shader/pos_color.vs.hlsl"
kind = "shader"
vertex_type = "poscol"
[[assets]]
name = "ps_pos_color"
path = "assets/shader/pos_color.ps.hlsl"
kind = "shader"
[[assets]]
name = "vs_fullscreen"
path = "assets/shader/fullscreen.vs.hlsl"
kind = "shader"
vertex_type = "posuv"

[[assets]]
name = "player"
path = "assets/image/ss_player.toml"
kind = "sprite_sheet"

[[assets]]
name = "font_7px"
path = "assets/image/font_7px_rgba.tga"
kind = "sprite_font"

[[assets]]
name = "metro"
path = "assets/image/metro_1080p.tga"
kind = "sprite"

[[assets]]
name = "rgba_test"
path = "assets/image/rgba.tga"
kind = "sprite"
