name: macOS
 
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master


jobs:
  xcode:
    runs-on: macos-10.15
    strategy:
      matrix:
        build_type: [Debug, RelWithDebInfo, MinSizeRel, Release] 
        xcode: [12.4, 12.3, 12.2, 12.1.1, 12.1, 12, 11.7, 11.6, 11.5, 11.4.1, 11.3.1, 11.2.1, 10.3]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - uses: actions/checkout@v2
      - name: CMake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -DTAU_BUILDINTERNALTESTS=On  -DTAU_BUILDTHIRDPARTYTESTS=On
        
      - name: Build
        run: cmake --build build --config=${{ matrix.build_type }} --parallel 10

      - name: Test (Internal)
        run: | 
          cd build/bin && ./TauInternalTests
      
      - name: Test (ThirdParty)
        run: |
          cd build/bin && ./TauThirdPartyTests_6502