#ifndef H_MAIN
#define H_MAIN

#define NULL_INDEX -1
#define TEMP_STRING_MAX 256

#define WINDOW_WIDTH 960
#define WINDOW_HEIGHT 720
#define WINDOW_WIDTH_HALF WINDOW_WIDTH/2
#define WINDOW_HEIGHT_HALF WINDOW_HEIGHT/2
#define TARGET_FPS 60
#define TARGET_FRAMETIME(x) 1.0/x

#endif
